name: mmtaz
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  http: ^0.12.0
  intro_slider: ^2.2.9
  gradient_app_bar: ^0.1.3
  carousel_slider: ^1.3.0
  marquee_widget: ^0.8.0
  wave: ^0.0.8
  shifting_tabbar: ^0.3.1
  circle_wheel_scroll: ^0.0.1+1
  pie_chart: ^3.1.1
  titled_navigation_bar: ^4.1.0
  flutter_custom_clippers: ^1.1.0
  animated_floatactionbuttons: ^0.1.0
  flutter_full_pdf_viewer: ^1.0.6
  cached_network_image: ^2.2.0+1
  shared_preferences: ^0.5.7+3
  connectivity: ^0.4.8+6
  font_awesome_flutter: ^8.8.1
  line_awesome_flutter: ^1.0.1
  flutter_svg: ^0.17.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - images/1.png
    - images/2.png
    - images/3.jpg
    - images/4.jpg
    - images/4.png
    - images/5.jpg
    - images/55.jpg
    - images/6.jpg
    - images/7.png
    - images/8.jpg
    - images/11.jpg
    - images/12.jpg
    - images/13.jpg
    - images/23.jpg
    - images/24.jpg
    - images/25.png
    - images/111.png
    - images/111.jpg
    - images/222.jpg
    - images/1111.jpg
    - images/1111.png
    - images/2222.png
    - images/3333.jpg
    - images/4444.jpg
    - images/55555.webp
    - images/6666.jpg
    - images/7777.jpg
    - images/8888.jpg
    - images/9999.jpg
    - images/owl.png
    - images/phone_number.png
    - images/verification_code.png
    - images/register.png
    - images/1.jpg
    - images/2.jpg
    - images/list.png
    - images/bac1.jpg
    - images/bac2.jpg
    - images/bac3.jpg
    - images/bac4.png
    - images/bac.png
    - images/back.png
    - images/Group_Chat.gif
    - images/Security.gif
    - images/Schedule.gif
    - images/Lastplans.gif
    - images/Market_launch.gif
    - images/Visual_data.gif
#----------------svg-----------------
    - svg/group-chat-animate.svg
  fonts:
    - family: Aviny
      fonts:
        - asset: fonts/aviny.ttf
    - family: iran
      fonts:
        - asset: fonts/iran.ttf
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
